#!/bin/bash

#=================================================
# GENERIC START
#=================================================
# IMPORT GENERIC HELPERS
#=================================================

# Keep this path for calling _common.sh inside the execution's context of backup and restore scripts
source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

#=================================================
# DECLARE DATA AND CONF FILES TO BACKUP
#=================================================
ynh_print_info --message="Declaring files to be backed up..."

#=================================================
# BACKUP THE DATA DIR
#=================================================

if [ "$include_data_dir_in_backup" -eq 1 ]; then
    ynh_backup --src_path="$data_dir" --is_big
else
    echo "Ommitting $data_dir from backup based on include_data_dir_in_backup configuration"
fi

#=================================================
# SPECIFIC BACKUP
#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup --src_path="/etc/smb/smb.d/$app.conf"

ynh_backup --src_path="/etc/avahi/services/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info --message="Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
