#!/bin/bash

source ../settings/scripts/_common.sh
source /usr/share/yunohost/helpers

ynh_print_info "Declaring files to be backed up..."

#=================================================
# BACKUP THE DATA DIR
#=================================================

ynh_backup "$data_dir"

#=================================================
# BACKUP VARIOUS FILES
#=================================================

ynh_backup "/etc/smb/smb.d/$app.conf"

ynh_backup "/etc/avahi/services/$app.service"

#=================================================
# END OF SCRIPT
#=================================================

ynh_print_info "Backup script completed for $app. (YunoHost will then actually copy those files to the archive)."
