#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================
ynh_script_progression "Removing system configurations related to $app..."

if ynh_hide_warnings yunohost service status smbd >/dev/null; then
	yunohost service remove smbd
fi

if ynh_hide_warnings yunohost service status avahi-daemon >/dev/null; then
	yunohost service remove avahi-daemon
fi

# Delete User from Samba
ynh_hide_warnings smbpasswd -x $app

ynh_safe_rm "/etc/smb/smb.d/$app.conf"
ynh_safe_rm "/etc/avahi/services/$app.service"

samba_sysadmin_update

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
