#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="smb.conf" --destination="/etc/smb/smb.d/$app.conf"
ynh_config_add --template="avahi-samba.service" --destination="/etc/avahi/services/$app.service"

samba_sysadmin_update
samba_sysadmin_add

#=================================================
# OPEN PORT 445
#=================================================
ynh_script_progression "Configuring firewall..."

ynh_hide_warnings yunohost firewall allow --no-upnp TCP 445 # Allow SMB access

#=================================================
# INTEGRATE SERVICE IN YUNOHOST
#=================================================
ynh_script_progression "Integrating service in YunoHost..."

yunohost service add smbd --needs_exposed_ports 445

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=smbd --action="reload"
ynh_systemctl --service=avahi-daemon --action="restart"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
